### ISSUE TITLE
Purple Link

### ISSUE THREAD

**Issue by asutton0821** [kgonzale/cbu-acm-webpage#1]
When you click one link, they all turn purple.

**Comment by kgonzale** [comment]
Screenshot, they shouldn't be turning any color. The box sizing is an issue due to margin: auto;

**Comment by asutton0821** [comment]
Okay. I'll include screenshots of before and after. Notice they all turn purple. I just clicked the "officers" link. 
![issue2](https://user-images.githubusercontent.com/21368321/36864533-8ddfb33a-1d52-11e8-990e-da7456108cbd.png)
![issue1](https://user-images.githubusercontent.com/21368321/36864534-8e1ce9a8-1d52-11e8-8580-03d51f661adc.png)

**Comment by asutton0821** [comment]
In the picture, you can see where I selected officers. It could just be something Linux does.

**Comment by kgonzale** [comment]
You are not running the latest version, please fork and retry with what is currently in the repo.
